# config.py - Company Configuration
# Update these values with your company information

COMPANY_CONFIG = {
    'name': 'Your Company Name',
    'address': '123 Business Street, City, State 12345',
    'phone': '+1 (555) 123-4567',
    'email': 'info@yourcompany.com',
    'website': 'www.yourcompany.com',
    'logo_path': 'static/logo.png',  # Place your logo image in static folder
    'system_name': 'Project Costing System',
    'report_footer': 'This report is confidential and generated by the Project Costing System.'
}

from config import COMPANY_CONFIG